---
kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Values.service.namespace }}
  name: {{ .Values.secret.name }}
data:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
