---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: momo
  name: {{ .Values.configmap.name }}
data:
  default.conf: |
    server {
      listen  80;
      root  /momo-store;
      include /etc/nginx/mime.types;

      location / {
          try_files $uri $uri/ /index.html;
      }

      location ~ ^/(categories|products|auth|metrics|orders) {                     
          proxy_pass http://momo-backend:8081;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
      }    
    }
