include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  VERSION: "0.1.${CI_PIPELINE_ID}"

stages:
  - build
  - test
  - release

build-frontend-docker-job:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/infra/docker/Dockerfile_frontend"
      --destination "${CI_REGISTRY_IMAGE}/momo-store-frontend:${VERSION}"
      --build-arg VERSION=$VERSION
      --cache=true

sonarqube-frontend-sast:
  stage: test
  dependencies:
    - build-frontend-docker-job
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  allow_failure: true
  script:
    - cd frontend
    - >
      sonar-scanner 
      -Dsonar.projectName=${SONAR_PROJECT_KEY_FRONT}
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_FRONT}
      -Dsonar.sources=.
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_FRONT}

release:
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  stage: release
  before_script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - crane tag $CI_REGISTRY_IMAGE/momo-store-frontend:${VERSION} latest