stages:
  - module-pipelines

# frontend:
#   stage: module-pipelines
#   trigger:
#     include: "frontend/.gitlab-ci.yml"
#     strategy: depend
#   only:
#     changes:
#       - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include: "backend/.gitlab-ci.yml"
    strategy: depend
  only:
    - backend-ci
  # only:
  #   changes:
  #     - backend/*