stages:
  - module-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include: "frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/*

backend:
  stage: module-pipelines
  trigger:
    include: "backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/*

argocd:
  stage: module-pipelines
  trigger:
    include: "infra/helm/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - infra/*