---
groups:
  - name: Sausage store rules
    rules:
    - alert: InstanceDown
      expr: up{app="momo-backend"} == 0
      for: 1m
      labels:
        severity: critical
        project: "momo-store"
        component: "Backend"
