networks:
  momo-store:
    driver: bridge

services:
  frontend:
    image: momo-store-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - momo-store

  backend:
    image: momo-store-backend:latest
    container_name: backend
    ports:
      - "8081:8081"
    networks:
      - momo-store