services:
  frontend:
    image: momo-store-frontend:latest
    container_name: frontend
    restart: always
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=http://localhost:8081
    ports:
      - "80:80"

  backend:
    image: momo-store-backend:latest
    container_name: backend
    expose:
      - "8081"