FROM node:16.20.0-alpine3.18 AS builder
WORKDIR /app
COPY frontend/ .
RUN npm install
RUN npm run build

FROM nginx:latest
WORKDIR /momo-store
COPY --from=builder /app/dist .
COPY infra/docker/nginx.conf /etc/nginx/conf.d/default.conf
