FROM node:16.20.0-alpine3.18 AS builder
WORKDIR /app
COPY frontend/ .
RUN npm ci && npm run build

FROM nginx:latest
WORKDIR /app
COPY --from=builder /app/dist .
RUN ls -la
WORKDIR /app/dist/
RUN ls -la


