FROM node:16.20.0-alpine3.18 AS builder
WORKDIR /app
COPY frontend/*.json ./
RUN npm install
COPY frontend/ .
RUN NODE_ENV=production VUE_APP_API_URL=/ npm run build

FROM nginx:stable-alpine
WORKDIR /momo-store/
COPY --from=builder /app/dist .
COPY infra/docker/nginx.conf /etc/nginx/conf.d/default.conf
