# config for local tests
networks:
  momo-store:
    driver: bridge

services:
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-026-35/momo-store/momo-store-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - momo-store

  backend:
    image: gitlab.praktikum-services.ru:5050/std-026-35/momo-store/momo-store-backend:latest
    container_name: backend
    ports:
      - "8081:8081"
    networks:
      - momo-store
