---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.deployment.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - image: {{ .Values.deployment.image }}
          name: backend
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          ports:
            - name: {{ .Values.deployment.name }}
              containerPort: {{ .Values.deployment.containerPort }}
      imagePullSecrets:
        - name: {{ .Values.secret.name }}
