---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'backend'
      metrics_path: '/metrics'
      scrape_interval: 5s
      static_configs:
        - targets: ['momo-backend:8081']
