apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-name-prometheus
  namespace: momo
spec:
  secretName: prometheus-secret
  issuerRef:
    # ClusterIssuer, созданный вместе с Yandex CloudDNS ACME webhook
    name: http01-clusterissuer-prometheus
    kind: ClusterIssuer
  dnsNames:
    # Домен должен входить в вашу публичную зону Cloud DNS
    - prometheus.wownage.ru