apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain-name-momo-store
  namespace: momo
spec:
  secretName: momo-store-secret
  issuerRef:
    # ClusterIssuer, созданный вместе с Yandex CloudDNS ACME webhook
    name: http01-clusterissuer-momo-store
    kind: ClusterIssuer
  dnsNames:
    # Домен должен входить в вашу публичную зону Cloud DNS
    - momo-store.wownage.ru