apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-clusterissuer-grafana
  namespace: momo
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pavelnaumenkowork@gmail.com
    privateKeySecretRef:
      name: momo-store-secret
    solvers:
    - http01:
        ingress:
          class: nginx
